### ISSUE TITLE
Lastest nuget version doesn't contain the latest fix

### ISSUE THREAD

**Issue by kvpt** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#15]
Hi @vain0x,

After updated to the latest version of the nuget package, I still have the issue fixed by my PR on my app.
So I used DotPeek to uncompile the latest version and found that the code doesn't contain my latest fix.

Uncompiled version :
![image](https://user-images.githubusercontent.com/1446221/84031658-5e452600-a996-11ea-81d3-45adc0a6c105.png)

Current source :
https://github.com/vain0x/DotNetKit.Wpf.AutoCompleteComboBox/blob/6553f3aa25c38066b4105db096461965dadbada4/DotNetKit.Wpf.AutoCompleteComboBox/Windows/Controls/AutoCompleteComboBox.xaml.cs#L187

I don't think this is intended, so can you release a new version with the fix ?

Thank you.

**Comment by vain0x** [comment]
@kvpt Sorry and thank you for pointing out!

**Comment by kvpt** [comment]
@vain0x No problem, errors happen and it's a free time project so no warranty.
Thanks you again for your responsiveness.
