### ISSUE TITLE
Strong name assembly

### ISSUE THREAD

**Issue by Cekdisout** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#24]
Hi, is there any changes to sign assembly with strong name? :)

**Comment by vain0x** [comment]
No, I'm not sure about signing.

**Comment by Cekdisout** [comment]
Why not? :)

**Comment by vain0x** [comment]
Signing seems to need some amount of work; but I'm uncertain how it's helpful or necessary. Pull request is welcome.

**Comment by Cekdisout** [comment]
Ok, will see if I can do this ;)

**Comment by vain0x** [comment]
Closing since it's been a while and I have no plan to support strong name signing for now. Feel free to reopen if someone want to discuss about this.
