### ISSUE TITLE
Drop down list always displayed?

### ISSUE THREAD

**Issue by melsawy93** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#25]
Hi, Is there a way to have the drop down always shown? It only shows when the box is not blank. Is there also a way to reject any input thats not part of the ItemsSource? Say I enter an invalid value or something.

**Comment by vain0x** [comment]
Thanks. Unfortunately this library does not have such features.

> there a way to have the drop down always shown?

This library doesn't match the use case.
This library closes the drop down on some condition, which prevents keeping the drop down shown.

note: this could be related to IsDropDownOpen and StaysOpenOnEdit

> Is there also a way to reject any input thats not part of the ItemsSource?

My idea is to subscribe `Keyboard.LostKeyboardFocus` to clear text box when ItemsSource doesn't contain SelectedItem.

note: it depends on when to reject and what to do on rejection

**Comment by vain0x** [comment]
(In other words: You can implement an always-shown drop down combobox without using this library and which I think is better way.)

Closing. Feel free to reopen if someone want to discuss about this issue.

**Comment by melsawy93** [comment]
Thanks for the followup. Its been almost a year since I made this question and my WPF knowledge has vastly increased haha.
