### ISSUE TITLE
Changing ItemsSource selects the first item

### ISSUE THREAD

**Issue by tmijail** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#27]
### Current behaviour:
Since the 1.5 update, whenever `ItemsSource` is changed, `SelectedItem` is set to the first item in `ItemsSource`. This overwrites any selection that the user might have previously made.

https://user-images.githubusercontent.com/6920322/233461419-f4abce3d-a7fc-4398-9e55-1f7ceb482bc0.mp4

### Expected behaviour:
If `SelectedItem` exists in the new `ItemsSource`, it shouldn't change. If it doesn't, the selection should be cleared.

### Steps to reproduce:
See the demo in [this branch](https://github.com/tmijail/DotNetKit.Wpf.AutoCompleteComboBox/tree/ItemsSource-bug-demo). Specifically, [this commit](https://github.com/vain0x/DotNetKit.Wpf.AutoCompleteComboBox/commit/54782cb7673270c6d27ad14bb9868855db5102d0).

**Comment by vain0x** [comment]
Thank you! Released in v1.6.0.
