### ISSUE TITLE
Unable to set background color 

### ISSUE THREAD

**Issue by Cellus250** [vain0x/DotNetKit.Wpf.AutoCompleteComboBox#31]
Hello thank you for the control. It works great. However, I have been unable to apply a background color to the control using the Background property. 

Is there a certain way this needs to be set or overridden? 

Thanks.

**Comment by vain0x** [comment]
@Cellus250 `AutoCompleteComboBox` is basically `ComboBox` with `IsEditable=True` except for behaviors. WPF combobox doesn't seem to support `Background`. (You could use ControlTemplate or something maybe?)

```xaml
    <ComboBox IsEditable="True" IsTextSearchEnabled="False" ItemsSource="{Binding Items}" Background="Blue" />
```

**Comment by Arrowka** [comment]
> Okay, that makes sense. Thanks for the support.

Hey. Did you find any solution for it?
